# Generated by Django 2.2.6 on 2020-04-20 11:25

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=30)),
                ('token', models.UUIDField(null=True)),
                ('contacts_id', django_mysql.models.ListTextField(models.IntegerField(), size=1000)),
                ('gps_id', django_mysql.models.ListTextField(models.IntegerField(), size=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='gp',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='users.User'),
        ),
        migrations.AlterField(
            model_name='gp_messages',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendergp', to='users.User'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='users.User'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='users.User'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
